CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    overview VARCHAR(3000) NOT NULL,
    poster_path VARCHAR(1000) NOT NULL,
    backdrop_path VARCHAR(1000) NOT NULL,
    release_date DATE NOT NULL,
    original_language VARCHAR(255) NOT NULL,
    tagline VARCHAR(255),
    vote_average DOUBLE PRECISION,
    vote_count INTEGER,
    runtime INTEGER,
    genres_csv VARCHAR(1000),
    casts_csv VARCHAR(6000)
);
